n = int(input("Digite um valor:"))
n1 = n*1
n2 = n*2
n3 = n*3
n4 = n*4
n5 = n*5
n6 = n*6
n7 = n*7
n8 = n*8
n9 = n*9
print("A sua tabuada é: {} x 1 = {}".format(n, n1))
print("A sua tabuada é: {} x 2 = {}".format(n, n2))
print("A sua tabuada é: {} x 3 = {}".format(n, n3))
print("A sua tabuada é: {} x 4 = {}".format(n, n4))
print("A sua tabuada é: {} x 5 = {}".format(n, n5))
print("A sua tabuada é: {} x 6 = {}".format(n, n6))
print("A sua tabuada é: {} x 7 = {}".format(n, n7))
print("A sua tabuada é: {} x 8 = {}".format(n, n8))
print("A sua tabuada é: {} x 9 = {}".format(n, n9))

